multitenancy_enabled: false

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      insecure: true
      access_key_id: loki
      secret_access_key: supersecret

compactor:
  data_dir: /mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

ingester:
  ring:
    replication_factor: 1

blocks_storage:
  backend: s3
  s3:
    bucket_name: mimir-blocks
  tsdb:
    dir: /mimir/tsdb
    flush_blocks_on_shutdown: true

ruler_storage:
  backend: s3
  s3:
    bucket_name: mimir-ruler

server:
  http_listen_port: 9009
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1